apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway-configuration      # name of the gateway
spec:
  selector:
    istio: ingressgateway     # use Istio default gateway implementation - label of instio ingressgateway pod in istio-system namespace
  servers:
  - port:
      number: 80              # port number
      name: http              # name of the port
      protocol: HTTP          # protocol 
    hosts:
    - "*"                     # Use the real Domain name of the external website in production
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: fleetman-webapp
  namespace: default
spec:
  hosts:
    - "*"                      # Add the domain name of the gateway, Use the real Domain name of the external website in production
  gateways: 
    - ingress-gateway-configuration                           # name of the gateway
  http:
    - route:
        - destination:
            host: fleetman-webapp                             # The Target DNS name - not FQDN
            subset: original
          weight: 100
        - destination:
            host: fleetman-webapp                             # The Target DNS name - not FQDN
            subset: experimental
          weight: 0
---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: fleetman-webapp
  namespace: default
spec:
  host: fleetman-webapp.default.svc.cluster.local
  subsets:
    - labels:
        version: original
      name: original
    - labels:
        version: experimental
      name: experimental