# This will enforce that ONLY traffic that is TLS is allowed between proxies
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "istio-system"         # destination namespace
spec:
  mtls:
    mode: STRICT                    # mutualTLS mode
